server:
  port: 5010

mybatis:
  type-aliases-package: com.mj.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  application:
    name: system-5010
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://106.13.29.202:3306/mj_sys?useUnicode=true&characterEncoding=utf-8
    username: root
    password: abc123456